---
- name: Installer et démarrer Nginx
  hosts: web
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
